import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import axios from "axios";
import cookieParser from "cookie-parser";
import cors from "cors";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());
  app.use(cookieParser());
  app.use(cors({
    origin: true,
    credentials: true
  }));

  // TikTok OAuth Endpoints
  app.get("/api/tiktok/auth-url", (req, res) => {
    const clientKey = process.env.TIKTOK_CLIENT_KEY;
    const host = req.get('host');
    const protocol = host?.includes('localhost') ? 'http' : 'https';
    const redirectUri = process.env.TIKTOK_REDIRECT_URI || `${protocol}://${host}/api/tiktok/callback`;
    
    if (!clientKey) {
      return res.status(500).json({ error: "TIKTOK_CLIENT_KEY not configured" });
    }

    const state = Math.random().toString(36).substring(7);
    const authUrl = `https://www.tiktok.com/v2/auth/authorize/?client_key=${clientKey}&scope=video.upload,video.publish,user.info.basic&response_type=code&redirect_uri=${encodeURIComponent(redirectUri)}&state=${state}`;
    
    res.json({ url: authUrl });
  });

  app.get("/api/tiktok/callback", async (req, res) => {
    const { code } = req.query;
    const clientKey = process.env.TIKTOK_CLIENT_KEY;
    const clientSecret = process.env.TIKTOK_CLIENT_SECRET;
    const host = req.get('host');
    const protocol = host?.includes('localhost') ? 'http' : 'https';
    const redirectUri = process.env.TIKTOK_REDIRECT_URI || `${protocol}://${host}/api/tiktok/callback`;

    if (!code) return res.status(400).send("No code provided");

    try {
      const response = await axios.post(
        "https://open.tiktokapis.com/v2/oauth/token/",
        new URLSearchParams({
          client_key: clientKey!,
          client_secret: clientSecret!,
          code: code as string,
          grant_type: "authorization_code",
          redirect_uri: redirectUri,
        }).toString(),
        { headers: { "Content-Type": "application/x-www-form-urlencoded" } }
      );

      const { access_token, open_id } = response.data;

      // Store in cookie for the iframe context
      res.cookie("tiktok_token", access_token, {
        httpOnly: true,
        secure: true,
        sameSite: "none",
        maxAge: 24 * 60 * 60 * 1000 // 24 hours
      });

      res.send(`
        <html>
          <body>
            <script>
              if (window.opener) {
                window.opener.postMessage({ type: 'TIKTOK_AUTH_SUCCESS' }, '*');
                window.close();
              } else {
                window.location.href = '/';
              }
            </script>
            <p>Authentication successful! You can close this window.</p>
          </body>
        </html>
      `);
    } catch (error: any) {
      console.error("TikTok Auth Error:", error.response?.data || error.message);
      res.status(500).send("Failed to exchange code for token");
    }
  });

  // Proxy endpoint to allow TikTok to access Gemini-generated videos
  app.get("/api/proxy-video", async (req, res) => {
    const videoUrl = req.query.url as string;
    if (!videoUrl) return res.status(400).send("No URL provided");

    try {
      const response = await axios({
        method: 'get',
        url: videoUrl,
        responseType: 'stream',
        headers: {
          'x-goog-api-key': process.env.API_KEY || process.env.GEMINI_API_KEY || '',
        }
      });

      res.setHeader('Content-Type', response.headers['content-type'] || 'video/mp4');
      response.data.pipe(res);
    } catch (error: any) {
      console.error("Proxy Error:", error.message);
      res.status(500).send("Failed to proxy video");
    }
  });

  // TikTok Direct Publish Endpoint
  app.post("/api/tiktok/publish", async (req, res) => {
    const token = req.cookies.tiktok_token;
    const { videoUrl, title } = req.body;

    if (!token) return res.status(401).json({ error: "Not authenticated with TikTok" });
    if (!videoUrl) return res.status(400).json({ error: "No video URL provided" });

    try {
      // Create a publicly accessible proxy URL for TikTok to pull from
      // Force https for Cloud Run environment
      const host = req.get('host');
      const protocol = host?.includes('localhost') ? 'http' : 'https';
      const proxyUrl = `${protocol}://${host}/api/proxy-video?url=${encodeURIComponent(videoUrl)}`;
      
      console.log("Publishing to TikTok with Proxy URL:", proxyUrl);

      // 1. Initialize the upload
      const initResponse = await axios.post(
        "https://open.tiktokapis.com/v2/post/publish/video/init/",
        {
          post_info: {
            title: title || "Generated by Marketing Engine",
            privacy_level: "PUBLIC_TO_EVERYONE"
          },
          source_info: {
            source: "PULL_FROM_URL",
            video_url: proxyUrl
          }
        },
        {
          headers: {
            "Authorization": `Bearer ${token}`,
            "Content-Type": "application/json"
          }
        }
      );

      res.json({ success: true, data: initResponse.data });
    } catch (error: any) {
      const errorData = error.response?.data;
      console.error("TikTok Publish Error:", JSON.stringify(errorData, null, 2) || error.message);
      
      // Provide more specific error messages to the frontend
      let message = "Failed to publish to TikTok";
      if (errorData?.error?.code === "access_token_invalid") {
        message = "TikTok session expired. Please reconnect your account.";
      } else if (errorData?.error?.code === "scope_not_authorized") {
        message = "Missing permissions. Please reconnect TikTok and allow 'Post videos'.";
      } else if (errorData?.error?.code === "spam_risk") {
        message = "TikTok flagged this as potential spam. Try changing the caption.";
      }

      res.status(500).json({ 
        error: message, 
        details: errorData,
        code: errorData?.error?.code
      });
    }
  });

  app.post("/api/tiktok/publish-status", async (req, res) => {
    const token = req.cookies.tiktok_token;
    const { publishId } = req.body;

    if (!token) return res.status(401).json({ error: "Not authenticated" });
    if (!publishId) return res.status(400).json({ error: "No publish ID provided" });

    try {
      const response = await axios.post(
        "https://open.tiktokapis.com/v2/post/publish/status/fetch/",
        { publish_id: publishId },
        {
          headers: {
            "Authorization": `Bearer ${token}`,
            "Content-Type": "application/json"
          }
        }
      );
      res.json(response.data);
    } catch (error: any) {
      console.error("TikTok Status Error:", error.response?.data || error.message);
      res.status(500).json({ error: "Failed to fetch status" });
    }
  });

  app.get("/api/tiktok/me", async (req, res) => {
    const token = req.cookies.tiktok_token;
    if (!token) return res.status(401).json({ error: "Not authenticated" });

    try {
      const response = await axios.get("https://open.tiktokapis.com/v2/user/info/?fields=display_name,avatar_url", {
        headers: { "Authorization": `Bearer ${token}` }
      });
      res.json(response.data);
    } catch (error) {
      res.status(401).json({ error: "Invalid token" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
