'use client';

import React from 'react';
import { motion } from 'motion/react';
import { ArrowLeft, FileText, CheckCircle } from 'lucide-react';
import Link from 'next/link';

export default function TermsOfServiceContent() {
  return (
    <div className="min-h-screen bg-mesh p-8 md:p-20 flex flex-col items-center">
      <motion.div
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        className="self-start mb-12"
      >
        <Link
          href="/"
          className="flex items-center gap-2 text-brand-600 font-bold hover:text-brand-800 transition-all bg-white/50 backdrop-blur-sm px-6 py-3 rounded-2xl shadow-sm border border-white"
        >
          <ArrowLeft size={20} />
          Back to Login
        </Link>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-4xl w-full glass p-10 md:p-16 rounded-[3rem] border border-white/50 shadow-2xl relative overflow-hidden"
      >
        <div className="absolute top-0 right-0 p-10 opacity-5 pointer-events-none">
          <FileText size={200} className="text-brand-500" />
        </div>

        <header className="mb-12 border-b border-brand-100 pb-10">
          <div className="flex items-center gap-4 mb-4">
            <div className="w-12 h-12 bg-brand-100 rounded-2xl flex items-center justify-center text-brand-600 shadow-inner">
              <FileText size={24} />
            </div>
            <h1 className="text-4xl md:text-5xl font-display font-bold text-brand-700 tracking-tight">Terms of Service</h1>
          </div>
          <p className="text-slate-500 text-lg">Last Updated: April 10, 2026</p>
        </header>

        <div className="space-y-12 text-slate-600 leading-relaxed">
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-brand-700 flex items-center gap-3">
              <span className="text-brand-400">01.</span> Acceptance of Terms
            </h2>
            <p>
              By accessing and using Marketing Engine, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the platform. Our mission is to provide powerful AI tools for marketing, and these terms ensure a fair and safe experience for everyone.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-brand-700 flex items-center gap-3">
              <span className="text-brand-400">02.</span> Description of Service
            </h2>
            <p>
              Marketing Engine is an AI-powered platform that helps users generate marketing copy, images, and videos, and provides TikTok analytics. The platform utilizes advanced models including Google Gemini to provide these services.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
              {[
                "AI Content Generation",
                "Social Media Automation",
                "Advanced Marketing Analytics",
                "Multi-platform Integration"
              ].map((item, i) => (
                <div key={i} className="flex items-center gap-3 bg-brand-50 p-4 rounded-2xl border border-brand-100">
                  <CheckCircle size={18} className="text-emerald-500 shrink-0" />
                  <span className="text-sm font-bold text-brand-700">{item}</span>
                </div>
              ))}
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-brand-700 flex items-center gap-3">
              <span className="text-brand-400">03.</span> User Accounts & Auth
            </h2>
            <p>
              You may be required to connect third-party accounts, such as TikTok, to utilize specific features like direct publishing and analytics. You are responsible for maintaining the security of your account and all activities that occur under your credentials.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-brand-700 flex items-center gap-3">
              <span className="text-brand-400">04.</span> Content & IP
            </h2>
            <p>
              Content generated by Marketing Engine&apos;s AI tools is provided for your use. While you retain ownership of your inputs, the underlying AI models and platform code are protected by intellectual property laws. You agree not to use the generated content for illegal purposes or to bypass platform restrictions.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-brand-700 flex items-center gap-3">
              <span className="text-brand-400">05.</span> Limitation of Liability
            </h2>
            <p className="p-6 bg-rose-50 rounded-3xl border border-rose-100 italic text-rose-700 text-sm">
              Marketing Engine provides its services &quot;as is&quot;. We are not responsible for any direct, indirect, or incidental damages resulting from your use of the platform or any inaccuracies in AI-generated content.
            </p>
          </section>
        </div>

        <footer className="mt-20 pt-10 border-t border-brand-100 text-center">
          <p className="text-slate-400 text-sm uppercase tracking-widest font-bold">© 2026 Marketing Engine • All Rights Reserved</p>
        </footer>
      </motion.div>
    </div>
  );
}
