import { NextRequest, NextResponse } from 'next/server';
import axios from 'axios';

export async function POST(req: NextRequest) {
  const token = req.cookies.get('tiktok_token')?.value;
  const { videoUrl, title } = await req.json();

  if (!token) return NextResponse.json({ error: "Not authenticated with TikTok" }, { status: 401 });
  if (!videoUrl) return NextResponse.json({ error: "No video URL provided" }, { status: 400 });

  try {
    const host = req.headers.get('host') || 'localhost:3000';
    const protocol = host.includes('localhost') ? 'http' : 'https';
    const proxyUrl = `${protocol}://${host}/api/tiktok/proxy-video?url=${encodeURIComponent(videoUrl)}`;

    console.log("Publishing to TikTok with Proxy URL:", proxyUrl);

    const initResponse = await axios.post(
      "https://open.tiktokapis.com/v2/post/publish/video/init/",
      {
        post_info: {
          title: title || "Generated by Marketing Engine",
          privacy_level: "PUBLIC_TO_EVERYONE"
        },
        source_info: {
          source: "PULL_FROM_URL",
          video_url: proxyUrl
        }
      },
      {
        headers: {
          "Authorization": `Bearer ${token}`,
          "Content-Type": "application/json"
        }
      }
    );

    return NextResponse.json({ success: true, data: initResponse.data });
  } catch (error: any) {
    const errorData = error.response?.data;
    console.error("TikTok Publish Error:", JSON.stringify(errorData, null, 2) || error.message);

    let message = "Failed to publish to TikTok";
    if (errorData?.error?.code === "access_token_invalid") {
      message = "TikTok session expired. Please reconnect your account.";
    } else if (errorData?.error?.code === "scope_not_authorized") {
      message = "Missing permissions. Please reconnect TikTok and allow 'Post videos'.";
    } else if (errorData?.error?.code === "spam_risk") {
      message = "TikTok flagged this as potential spam. Try changing the caption.";
    }

    return NextResponse.json({
      error: message,
      details: errorData,
      code: errorData?.error?.code
    }, { status: 500 });
  }
}
